[{
    "id": "1",
    "name": "尽头",
    "author": "唐诺",
    "country": "中国台湾"
}, {
    "id": "2",
    "name": "想见看见听见",
    "author": "阮义忠",
    "country": "中国台湾"
}, {
    "id": "3",
    "name": "大数据时代",
    "author": "维克托•迈尔•舍恩伯格",
    "country": "英国"
}, {
    "id": "4",
    "name": "拥有七个名字的女孩：一个北韩叛逃者的真实故事",
    "author": "李晛瑞",
    "country": "韩国"
}, {
    "id": "5",
    "name": "三体",
    "author": "刘慈欣",
    "country": "中国"
}, {
    "id": "6",
    "name": "北鸢",
    "author": "葛亮",
    "country": "中国"
}, {
    "id": "7",
    "name": "天才在左 疯子在右",
    "author": "古龙",
    "country": "中国台湾"
}, {
    "id": "8",
    "name": "质数的孤独",
    "author": "古龙",
    "country": "中国台湾"
}, {
    "id": "9",
    "name": "黑客与画家",
    "author": "古龙",
    "country": "中国台湾"
}]